# Generated by Django 3.0.10 on 2020-09-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery_model', '0003_auto_20200713_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltaskmeta',
            name='object_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
